# Generated by Django 5.0.1 on 2024-02-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0002_product_date_product_image_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='abouttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messi', models.CharField(max_length=30)),
                ('ronaldo', models.TextField()),
            ],
        ),
    ]
