# Generated by Django 5.0.1 on 2024-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0003_abouttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttable',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
