# Generated by Django 5.0.1 on 2024-02-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0006_remove_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mainpage',
            new_name='mainpag',
        ),
        migrations.RenameField(
            model_name='abouttable',
            old_name='messi',
            new_name='lmessi',
        ),
        migrations.RenameField(
            model_name='mainpag',
            old_name='messi',
            new_name='lmessi',
        ),
    ]
