# Generated by Django 5.0.1 on 2024-02-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0008_rename_mainpag_mainpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
