# Generated by Django 5.0.1 on 2024-02-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0009_mainpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messi.product'),
        ),
    ]
