# Generated by Django 5.0.1 on 2024-02-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0010_mainpage_price_mainpage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='mainpage',
        ),
    ]
