# Generated by Django 5.0.1 on 2024-02-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0011_contact_delete_mainpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactt',
        ),
    ]
