# Generated by Django 5.0.1 on 2024-02-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0013_contact_delete_contactt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='contact_admin',
        ),
    ]
