# Generated by Django 5.0.1 on 2024-02-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0014_rename_contact_contact_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_admin',
            old_name='email',
            new_name='iemail',
        ),
        migrations.RenameField(
            model_name='contact_admin',
            old_name='message',
            new_name='imessage',
        ),
        migrations.RenameField(
            model_name='contact_admin',
            old_name='name',
            new_name='iname',
        ),
    ]
