# Generated by Django 5.0.1 on 2024-02-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0015_rename_email_contact_admin_iemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_admin',
            name='iimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
