# Generated by Django 5.0.1 on 2024-02-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0016_contact_admin_iimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_admin',
            name='iimage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
