# Generated by Django 5.0.1 on 2024-02-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0017_alter_contact_admin_iimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_admin',
            old_name='iimage',
            new_name='image',
        ),
    ]
