# Generated by Django 5.0.1 on 2024-02-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0018_rename_iimage_contact_admin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_admin',
            name='image',
        ),
        migrations.AddField(
            model_name='contact_admin',
            name='iimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
