# Generated by Django 5.0.1 on 2024-02-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0019_remove_contact_admin_image_contact_admin_iimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_admin',
            name='iemail',
        ),
        migrations.AddField(
            model_name='contact_admin',
            name='iprice',
            field=models.FloatField(null=True),
        ),
    ]
